#!/usr/bin/env bash
# write a Bash script that displays lines containing the bash word, 
# thus allowing you to easily get the PID of your Bash process.
# The third line of your script must be # shellcheck disable=SC2009.
# shellcheck disable=SC2059
ps -f -aux | grep "bash"
