#!/usr/bin/env bash
# Configures an Ubuntu server and change the IP localhost and resolve FB IP.

sudo cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '/facebook.com/d' ~/hosts.new
sed -i '$ a 8.8.8.8\t\tfacebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
