#!/usr/bin/env bash
# Configures an Ubuntu server and change the IP localhost and resolve FB IP.

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
sed -i '/facebook.com/d' ~/hosts.new
sed -i '$ a 8.8.8.8\t\tfacebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
