#!/usr/bin/env bash
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080

sudo pkill apache2
sudo chmod 664 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
