#!/usr/bin/env bash
# Same has previuos, nginx running as user
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www.data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
