#!/usr/bin/env bash
# Requirements: 1.Your SSH client configuration must be configured to use the private key ~/.ssh/school
# 2. Your SSH client configuration must be configured to refuse to authenticate using a password

IdentityFile ~/.ssh/school
PasswordAuthentication no
